# Generated by Django 4.2 on 2023-04-19 14:40

import autoslug.fields
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import news.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competition', '0005_remove_fotos_album_remove_news_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
            options={
                'verbose_name': 'Categoria da noticia',
                'verbose_name_plural': 'Categorias das noticias',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Editado em')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Título')),
                ('cover', models.ImageField(blank=True, null=True, upload_to=news.models.get_path_cover_news)),
                ('content', ckeditor.fields.RichTextField(verbose_name='Texto')),
                ('publication_date', models.DateTimeField(blank=True, help_text='O sistema só irá liberar quando chegar na data de liberação.', null=True, verbose_name='Data de publicação')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=150, populate_from='title', unique=True, verbose_name='Link')),
                ('status', models.PositiveIntegerField(choices=[(1, 'RASCUNHO'), (3, 'ATIVADA'), (2, 'DESATIVADA')], default=1, verbose_name='Status')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_autor', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.categorynews', verbose_name='Categoria')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.edition', verbose_name='Edição')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Editado por')),
            ],
        ),
    ]
