# Generated by Django 4.2 on 2023-04-22 12:37

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Notícia', 'verbose_name_plural': 'Notícias'},
        ),
        migrations.AlterField(
            model_name='news',
            name='cover',
            field=models.ImageField(null=True, upload_to=news.models.get_path_cover_news, verbose_name='Imagem de destaque'),
        ),
        migrations.AlterField(
            model_name='news',
            name='publication_date',
            field=models.DateTimeField(blank=True, help_text='O sistema só irá liberar quando chegar na data de publicação.', null=True, verbose_name='Data de publicação'),
        ),
    ]
