# Generated by Django 4.2 on 2023-04-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_options_alter_news_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200, null=True, verbose_name='Título'),
        ),
    ]
