# Generated by Django 4.2 on 2023-04-19 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_album_categorynews_websiteedition_page_news_fotos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionModality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='ModalityEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('foto', models.ImageField(upload_to=None)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.edition', verbose_name='Edição')),
                ('modality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.competitionmodality', verbose_name='Modalidade')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryModality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_vacancies', models.IntegerField(blank=True, null=True, verbose_name='Quantidade de vagas')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.competitioncategory', verbose_name='Categoria')),
                ('modality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.competitionmodality', verbose_name='Modalidade')),
            ],
        ),
    ]
