# Generated by Django 4.2 on 2023-04-19 14:40

import competition.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_competitioncategory_competitionmodality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotos',
            name='album',
        ),
        migrations.RemoveField(
            model_name='news',
            name='author',
        ),
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
        migrations.RemoveField(
            model_name='news',
            name='edition',
        ),
        migrations.RemoveField(
            model_name='page',
            name='edition',
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Banner', 'verbose_name_plural': 'Banners'},
        ),
        migrations.AlterModelOptions(
            name='categorymodality',
            options={'verbose_name': 'Categoria da Modalidade', 'verbose_name_plural': 'Categorias das Modalidades'},
        ),
        migrations.AlterModelOptions(
            name='competitioncategory',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='competitionmodality',
            options={'verbose_name': 'Modalidade', 'verbose_name_plural': 'Modalidades'},
        ),
        migrations.AlterModelOptions(
            name='edition',
            options={'verbose_name': 'Edição', 'verbose_name_plural': 'Edições'},
        ),
        migrations.AlterModelOptions(
            name='federation',
            options={'verbose_name': 'Federação', 'verbose_name_plural': 'Federações'},
        ),
        migrations.AlterModelOptions(
            name='modalityedition',
            options={'verbose_name': 'Modalidade da Edição', 'verbose_name_plural': 'Modalidades das Edições'},
        ),
        migrations.AlterModelOptions(
            name='sponsor',
            options={'verbose_name': 'Patrocinador', 'verbose_name_plural': 'Patrocinadores'},
        ),
        migrations.AlterModelOptions(
            name='websiteedition',
            options={'verbose_name': 'Configuração da Edição', 'verbose_name_plural': 'Configurações das Edições'},
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner',
            field=models.ImageField(upload_to=competition.models.get_path_banner, verbose_name='Banner'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='position',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'BANNER PRICIPAL'), (2, 'BACKGROUND DADOS'), (3, 'BACKGROUND EXPERIÊNCIA'), (4, 'BACKGROUND AÇÕES'), (5, 'BACKGROUND PERGUNTAS')], null=True, verbose_name='Posição'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'RASCUNHO'), (3, 'ATIVADA'), (2, 'DESATIVADA')], default=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'CERAPIO'), (2, 'PIOCERA')], default=1, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='banner',
            field=models.ImageField(upload_to=competition.models.get_path_sponsor_banner),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(upload_to=competition.models.get_path_sponsor_logo),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome do patrocinador'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='type',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'PATROCINADOR'), (2, 'CO-PATROCINADOR'), (3, 'APOIO')], null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='websiteedition',
            name='number_days_previous_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade de dias no ano anterior'),
        ),
        migrations.AlterField(
            model_name='websiteedition',
            name='number_km_previous_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade de km ano anterior'),
        ),
        migrations.AlterField(
            model_name='websiteedition',
            name='number_participants_previous_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade de participantes no ano anterior'),
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='CategoryNews',
        ),
        migrations.DeleteModel(
            name='Fotos',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
