# Generated by Django 4.2 on 2023-04-20 01:00

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0005_remove_fotos_album_remove_news_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionmodality',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=1, editable=False, max_length=150, populate_from='name', unique=True, verbose_name='Link'),
            preserve_default=False,
        ),
    ]
