# Generated by Django 4.2 on 2023-04-20 02:00

import autoslug.fields
import competition.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0006_competitionmodality_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitioncategory',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=1, editable=False, max_length=150, populate_from='name', unique=True, verbose_name='Link'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modalityedition',
            name='foto',
            field=models.ImageField(upload_to=competition.models.get_path_modality_competition),
        ),
    ]
