# Generated by Django 4.2 on 2023-04-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0008_alter_websiteedition_number_participants_previous_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteedition',
            name='number_km_previous_year',
            field=models.PositiveIntegerField(blank=True, help_text='Colocar apenas número sem o milhar. Ex: 15 se for 15 mil.', null=True, verbose_name='Quantidade de km ano anterior'),
        ),
    ]
