# Generated by Django 4.2 on 2023-04-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0009_alter_websiteedition_number_km_previous_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='position',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'BANNER PRICIPAL'), (2, 'BANNER TEXTO'), (3, 'BANNER OPÇÕES DE ESPORTES'), (4, 'BACKGROUND DADOS'), (5, 'BACKGROUND EXPERIÊNCIA'), (6, 'BACKGROUND AÇÕES'), (7, 'BACKGROUND PERGUNTAS')], null=True, verbose_name='Posição'),
        ),
    ]
