# Generated by Django 4.2 on 2023-04-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0010_alter_banner_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='position',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'BANNER PRICIPAL (1741x743)'), (2, 'BANNER TEXTO (1440x121)'), (3, 'BANNER OPÇÕES DE ESPORTES (4 banners - 288x124)'), (4, 'BACKGROUND DADOS'), (5, 'BACKGROUND EXPERIÊNCIA'), (6, 'BACKGROUND AÇÕES'), (7, 'BACKGROUND PERGUNTAS')], null=True, verbose_name='Posição'),
        ),
        migrations.AlterField(
            model_name='websiteedition',
            name='number_km_previous_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade de km ano anterior'),
        ),
    ]
