# Generated by Django 4.2 on 2023-04-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0012_alter_banner_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='title',
            field=models.CharField(help_text='Texto para opção de banner de esporte.', max_length=20, null=True, verbose_name='Titulo'),
        ),
    ]
