# Generated by Django 4.2 on 2023-04-21 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0013_banner_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodality',
            name='modality',
        ),
        migrations.AddField(
            model_name='categorymodality',
            name='modality_edition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='competition.modalityedition', verbose_name='Modalidade'),
        ),
    ]
