# Generated by Django 4.2 on 2023-04-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0010_typecompetitor_alter_competitorsregistration_type'),
        ('competition', '0015_alter_banner_options_alter_federation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalityedition',
            name='type_competitors',
            field=models.ManyToManyField(to='competitor.typecompetitor'),
        ),
    ]
