# Generated by Django 4.2 on 2023-04-24 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0011_alter_typecompetitor_name'),
        ('competition', '0017_alter_modalityedition_type_competitors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalityedition',
            name='type_competitors',
            field=models.ManyToManyField(blank=True, help_text='Adicione aqui os tipos de competidores que serão necessários na inscrição nessa modalidade', null=True, to='competitor.typecompetitor', verbose_name='Tipo de competidores'),
        ),
    ]
