# Generated by Django 4.2 on 2023-04-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0012_alter_registration_tire_year'),
        ('competition', '0018_alter_modalityedition_type_competitors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalityedition',
            name='type_competitors',
            field=models.ManyToManyField(help_text='Adicione aqui os tipos de competidores que serão necessários na inscrição nessa modalidade', to='competitor.typecompetitor', verbose_name='Tipo de competidores'),
        ),
    ]
