# Generated by Django 4.2 on 2023-04-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0019_alter_modalityedition_type_competitors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='registration_end_date',
            field=models.DateTimeField(verbose_name='Data final para inscrição'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='registration_start_date',
            field=models.DateTimeField(verbose_name='Data início para inscrição'),
        ),
    ]
