# Generated by Django 4.2 on 2023-04-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0020_alter_edition_registration_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='edition_date',
            field=models.DateTimeField(verbose_name='Data da edição'),
        ),
    ]
