# Generated by Django 4.2 on 2023-04-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0021_alter_edition_edition_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalityedition',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='Irá ser usado para ordenação nas telas necessárias', verbose_name='Ordem / Posição'),
        ),
    ]
