# Generated by Django 4.2 on 2023-04-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0022_modalityedition_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='event_end_date',
            field=models.DateTimeField(null=True, verbose_name='Data final do evento'),
        ),
        migrations.AddField(
            model_name='edition',
            name='event_start_date',
            field=models.DateTimeField(null=True, verbose_name='Data inicial do evento'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='edition_date',
            field=models.DateTimeField(verbose_name='Data de lançamento'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='registration_start_date',
            field=models.DateTimeField(verbose_name='Data inicial para inscrição'),
        ),
    ]
