# Generated by Django 4.2 on 2023-04-28 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0023_edition_event_end_date_edition_event_start_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='banner',
            unique_together={('edition', 'position')},
        ),
    ]
