# Generated by Django 4.2 on 2023-05-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0025_banner_created_at_banner_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodality',
            name='has_age',
            field=models.BooleanField(default=False, verbose_name='Tem faixa etária'),
        ),
        migrations.AddField(
            model_name='categorymodality',
            name='max_age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Idade máxima'),
        ),
        migrations.AddField(
            model_name='categorymodality',
            name='min_age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Idade mínima'),
        ),
    ]
