# Generated by Django 4.2 on 2023-05-05 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0026_categorymodality_has_age_categorymodality_max_age_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='banner',
            unique_together=set(),
        ),
    ]
