# Generated by Django 4.2 on 2023-05-05 19:01

import competition.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0027_alter_banner_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=competition.models.get_path_sponsor_banner),
        ),
    ]
