# Generated by Django 4.2 on 2023-05-07 01:15

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0030_alter_banner_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='term',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Termo de responsabilidade'),
        ),
    ]
