# Generated by Django 4.2 on 2023-05-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0031_edition_term'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitioncategory',
            options={'ordering': ('order',), 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AddField(
            model_name='competitioncategory',
            name='order',
            field=models.IntegerField(blank='True', null='True', verbose_name='Ordem'),
            preserve_default='True',
        ),
    ]
