# Generated by Django 4.2 on 2023-05-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0033_alter_categorymodality_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionmodality',
            name='is_apoio_zequinha',
            field=models.BooleanField(default=False, help_text='Marque a opção se for referente ao cadastro desse tipo pois irá aparecer um formulário exclusivo.', verbose_name='Zequinha/Apoio'),
        ),
    ]
