# Generated by Django 4.2 on 2023-09-04 01:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0036_modalityedition_whatsapp_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de término'),
        ),
        migrations.AddField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='banner',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem'),
        ),
        migrations.AddField(
            model_name='banner',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de início'),
        ),
    ]
