# Generated by Django 4.2 on 2023-04-19 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial', '0001_initial'),
        ('competitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.lot', verbose_name='Lote'),
        ),
        migrations.AddField(
            model_name='registration',
            name='pilot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Piloto'),
        ),
        migrations.AddField(
            model_name='registration',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='competitor.team', verbose_name='Equipe'),
        ),
        migrations.AddField(
            model_name='copilotregistration',
            name='copilot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Co-piloto'),
        ),
        migrations.AddField(
            model_name='copilotregistration',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitor.registration', verbose_name='Inscrição'),
        ),
    ]
