# Generated by Django 4.2 on 2023-04-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0004_competitorsregistration_alter_document_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitorsregistration',
            name='registration_number',
        ),
        migrations.AddField(
            model_name='registration',
            name='registration_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de inscrição'),
        ),
    ]
