# Generated by Django 4.2 on 2023-04-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0005_remove_competitorsregistration_registration_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitorsregistration',
            name='type',
            field=models.IntegerField(choices=[(1, 'Piloto'), (2, 'Co-Piloto'), (3, 'Zequinha')], default=1, verbose_name='Tipo'),
        ),
    ]
