# Generated by Django 4.2 on 2023-04-23 01:23

import competitor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0007_alter_registration_sponsorship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='model',
            field=models.FileField(blank=True, null=True, upload_to=competitor.models.get_path_model_documentation, verbose_name='Modelo do Documento'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
