# Generated by Django 4.2 on 2023-04-23 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0009_alter_registrationdocuments_document_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeCompetitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipo do Competidor',
                'verbose_name_plural': 'Tipo dos Competidores',
            },
        ),
        migrations.AlterField(
            model_name='competitorsregistration',
            name='type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='competitor.typecompetitor', verbose_name='Tipo'),
        ),
    ]
