# Generated by Django 4.2 on 2023-04-23 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0011_alter_typecompetitor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='tire_year',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Aro do pneu'),
        ),
    ]
