# Generated by Django 4.2 on 2023-04-28 00:43

import competitor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0012_alter_registration_tire_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='registration_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de inscrição'),
        ),
    ]
