# Generated by Django 4.2 on 2023-05-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0015_tirebrand_vehiclebrand_remove_registration_tire_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='registration_number',
            field=models.CharField(default=None, max_length=12, unique=True, verbose_name='Número de inscrição'),
            preserve_default=False,
        ),
    ]
