# Generated by Django 4.2 on 2023-05-06 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0016_alter_registration_registration_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationdocuments',
            name='registration',
        ),
        migrations.AddField(
            model_name='registrationdocuments',
            name='competitor_registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='competitor.competitorsregistration', verbose_name='Inscrição do competidor'),
        ),
    ]
