# Generated by Django 4.2 on 2023-05-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0017_remove_registrationdocuments_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='member',
            field=models.CharField(help_text='O que você é na equipe?', max_length=150, null=True, verbose_name='Membro'),
        ),
    ]
