# Generated by Django 4.2 on 2023-05-06 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competitor', '0018_team_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='member',
        ),
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_position', models.CharField(help_text='O que você é na equipe?', max_length=150, null=True, verbose_name='Posição do membro')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitor.team', verbose_name='Equipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Membro')),
            ],
            options={
                'verbose_name': 'Integrante da Equipe',
                'verbose_name_plural': 'Integrantes das Equipes',
            },
        ),
    ]
