# Generated by Django 4.2 on 2023-05-07 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0019_remove_team_member_teammembers'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdocuments',
            name='approval_status_changed',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
