# Generated by Django 4.2 on 2023-05-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0021_registration_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembers',
            name='member_position',
            field=models.PositiveIntegerField(choices=[(1, 'Chefe'), (2, 'Membro'), (3, 'Zequinha'), (4, 'Apoio')], help_text='O que você é na equipe?', null=True, verbose_name='Posição do membro'),
        ),
    ]
