# Generated by Django 4.2 on 2023-07-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0024_checklist_competitorchecklist_checklistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistitem',
            name='valid',
        ),
        migrations.AddField(
            model_name='competitorchecklist',
            name='check_list_item_concluded',
            field=models.ManyToManyField(to='competitor.checklistitem', verbose_name='Itens concluídos'),
        ),
    ]
