# Generated by Django 4.2 on 2023-07-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0025_remove_checklistitem_valid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitorchecklist',
            name='check_list_item_concluded',
            field=models.ManyToManyField(blank=True, to='competitor.checklistitem', verbose_name='Itens concluídos'),
        ),
    ]
