# Generated by Django 4.2 on 2023-07-20 14:42

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0026_alter_competitorchecklist_check_list_item_concluded'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Documentação')),
                ('competitor_registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='competitor.competitorsregistration', verbose_name='Inscrição do competidor')),
            ],
        ),
    ]
