# Generated by Django 4.2 on 2023-09-04 20:07

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0029_checklistitem_models_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorCheckListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_image', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='Imagem de Confirmação')),
                ('check_list_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitor.checklistitem', verbose_name='Item da Checklist')),
                ('competitor_checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitor.competitorchecklist', verbose_name='Checklist do Competidor')),
            ],
            options={
                'verbose_name': 'Item da Checklist do Competidor',
                'verbose_name_plural': 'Itens das Checklists dos Competidores',
            },
        ),
    ]
