version: '3.7'
services:
  piocera_prd:
    container_name: piocera_prd
    build:
      context: ../
      dockerfile: Docker/Dockerfile
    ports:
      - '8010:8000'
    volumes:
      - ../public:/home/radical360/dev/public/media/
    restart: always