# Generated by Django 4.2 on 2023-04-19 14:40

from django.db import migrations, models
import django.db.models.deletion
import image_bank.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competition', '0005_remove_fotos_album_remove_news_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('status', models.PositiveIntegerField(choices=[(1, 'RASCUNHO'), (3, 'ATIVADA'), (2, 'DESATIVADA')], default=1, verbose_name='Status')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.edition', verbose_name='Edição')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albuns',
            },
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('photo', models.ImageField(upload_to=image_bank.models.get_path_photo_album)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_bank.album', verbose_name='Album')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
            },
        ),
    ]
