# Generated by Django 4.2 on 2023-04-23 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_bank', '0002_remove_photos_album_album_date_subalbum_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'Categoria do album', 'verbose_name_plural': 'Categorias dos albuns'},
        ),
        migrations.AlterModelOptions(
            name='subalbum',
            options={'verbose_name': 'Album', 'verbose_name_plural': 'Albuns'},
        ),
        migrations.AlterField(
            model_name='photos',
            name='subalbum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='image_bank.subalbum', verbose_name='Album'),
        ),
        migrations.AlterField(
            model_name='subalbum',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_bank.album', verbose_name='Categoria'),
        ),
    ]
