# Generated by Django 4.2 on 2023-04-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_bank', '0003_alter_album_options_alter_subalbum_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='legend',
            field=models.CharField(max_length=200, null=True, verbose_name='Legenda'),
        ),
    ]
