# Generated by Django 4.2 on 2023-04-26 18:39

from django.db import migrations, models
import image_bank.models


class Migration(migrations.Migration):

    dependencies = [
        ('image_bank', '0004_photos_legend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='photo',
            field=models.ImageField(upload_to=image_bank.models.get_path_photo_album, verbose_name='Foto'),
        ),
    ]
