# Generated by Django 4.2 on 2023-05-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_bank', '0006_album_created_at_album_updated_at_photos_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('order',), 'verbose_name': 'Categoria do album', 'verbose_name_plural': 'Categorias dos albuns'},
        ),
        migrations.AddField(
            model_name='album',
            name='order',
            field=models.IntegerField(blank='True', null='True', verbose_name='Ordem'),
            preserve_default='True',
        ),
    ]
