# Generated by Django 4.2 on 2023-05-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_bank', '0007_alter_album_options_album_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subalbum',
            options={'ordering': ('order',), 'verbose_name': 'Album', 'verbose_name_plural': 'Albuns'},
        ),
        migrations.AddField(
            model_name='subalbum',
            name='order',
            field=models.IntegerField(blank='True', null='True', verbose_name='Ordem'),
            preserve_default='True',
        ),
    ]
