# Generated by Django 4.2 on 2023-04-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_apelido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='apelido',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='user',
            name='allergy',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Alergia'),
        ),
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AddField(
            model_name='user',
            name='blood_type',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tipo sanguineo'),
        ),
        migrations.AddField(
            model_name='user',
            name='cep',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='user',
            name='clothing',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Vestuário'),
        ),
        migrations.AddField(
            model_name='user',
            name='cnh',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='CNH'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='user',
            name='federation',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Federação'),
        ),
        migrations.AddField(
            model_name='user',
            name='health_insurance_plan',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Plano de saúde'),
        ),
        migrations.AddField(
            model_name='user',
            name='lgpd_acceptance',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Aceite LGPD'),
        ),
        migrations.AddField(
            model_name='user',
            name='name_emergency_contact',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome de contato emergencial'),
        ),
        migrations.AddField(
            model_name='user',
            name='national_license',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Licença nacional'),
        ),
        migrations.AddField(
            model_name='user',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Apelido'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='user',
            name='rg',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='user',
            name='uf',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='UF'),
        ),
    ]
