# Generated by Django 4.2 on 2023-04-19 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
        ('users', '0003_remove_user_apelido_user_address_user_allergy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Alergia')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True, verbose_name='Tipo sanguineo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='clothing',
            field=models.CharField(blank=True, choices=[('PPM', 'PP Masculino'), ('PM', 'P Masculino'), ('MM', 'M Masculino'), ('GM', 'G Masculino'), ('GGM', 'GG Masculino'), ('XGM', 'XG Masculino'), ('PPF', 'PP Feminino'), ('PF', 'P Feminino'), ('MF', 'M Feminino'), ('GF', 'G Feminino'), ('GGF', 'GG Feminino'), ('XGF', 'XG Feminino')], max_length=3, null=True, verbose_name='Vestuário'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='user',
            name='federation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='competition.federation', verbose_name='Federação afiliado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lgpd_acceptance',
            field=models.BooleanField(default=False, verbose_name='Aceite LGPD'),
        ),
        migrations.AlterField(
            model_name='user',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rg',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='user',
            name='allergy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.allergy', verbose_name='Alergia'),
        ),
    ]
