# Generated by Django 4.2 on 2023-04-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_allergy_user_city_alter_user_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_foto',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
