# Generated by Django 4.2 on 2023-04-19 14:40

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_profile_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allergy',
            options={'verbose_name': 'Alergia', 'verbose_name_plural': 'Alergias'},
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_foto',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.get_path, verbose_name='Foto de perfil'),
        ),
    ]
