# Generated by Django 4.2 on 2023-04-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_emergency_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='national_license',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Licença Nacional CBA'),
        ),
    ]
