# Generated by Django 4.2 on 2023-04-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_national_license'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='allergy',
        ),
        migrations.AddField(
            model_name='user',
            name='allergy',
            field=models.ManyToManyField(blank=True, null=True, to='users.allergy', verbose_name='Alergia'),
        ),
    ]
