# Generated by Django 4.2 on 2023-04-24 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_allergy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='allergy',
        ),
        migrations.AddField(
            model_name='user',
            name='allergy',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Alergia'),
        ),
    ]
