# Generated by Django 4.2 on 2023-04-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_user_allergy_user_allergy'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='customer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Id Asaas'),
        ),
    ]
