# Generated by Django 4.2 on 2023-04-19 14:40

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competition', '0005_remove_fotos_album_remove_news_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
            options={
                'verbose_name': 'Categoria da página',
                'verbose_name_plural': 'Categorias das páginas',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Texto')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=150, populate_from='title', unique=True, verbose_name='Link')),
                ('status', models.PositiveIntegerField(choices=[(1, 'RASCUNHO'), (3, 'ATIVADA'), (2, 'DESATIVADA')], default=1, verbose_name='Status')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.edition', verbose_name='Edição')),
                ('menu_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flat_pages.categorypage', verbose_name='Categoria do menu')),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': 'Páginas',
            },
        ),
    ]
