# Generated by Django 4.2 on 2023-04-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat_pages', '0002_categorypage_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='Irá ser usado para ordenação nos submenus', verbose_name='Ordem / Posição'),
        ),
    ]
