# Generated by Django 4.2 on 2023-05-17 17:42

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('flat_pages', '0006_alter_page_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Texto'),
        ),
    ]
