# Generated by Django 4.2 on 2023-07-25 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat_pages', '0007_alter_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='external_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link Externo'),
        ),
    ]
