# Generated by Django 4.2 on 2023-04-19 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competition', '0004_competitioncategory_competitionmodality_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, verbose_name='Nome do modelo')),
                ('quantity_lots', models.IntegerField(verbose_name='Quantidade de lotes')),
                ('price', models.FloatField(verbose_name='Valor')),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Valor')),
                ('start_date', models.DateTimeField(verbose_name='Data de início')),
                ('end_date', models.DateTimeField(verbose_name='Data de encerramento')),
                ('category_modality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.categorymodality', verbose_name='Categoria-Modalidade')),
            ],
        ),
    ]
