# Generated by Django 4.2 on 2023-04-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotmodel',
            name='percentage_accretion',
            field=models.FloatField(default=1, verbose_name='% de acréscimo'),
            preserve_default=False,
        ),
    ]
