# Generated by Django 4.2 on 2023-04-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_lotmodel_percentage_accretion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lot',
            options={'verbose_name': 'Lote', 'verbose_name_plural': 'Lotes'},
        ),
        migrations.AlterModelOptions(
            name='lotmodel',
            options={'verbose_name': 'Modelo de lote', 'verbose_name_plural': 'Modelos de lote'},
        ),
        migrations.AlterField(
            model_name='lot',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='lotmodel',
            name='percentage_accretion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='% de acréscimo'),
        ),
        migrations.AlterField(
            model_name='lotmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='lotmodel',
            name='quantity_lots',
            field=models.IntegerField(default=3, verbose_name='Quantidade de lotes'),
        ),
    ]
