# Generated by Django 4.2 on 2023-04-23 02:11

import django.core.validators
from django.db import migrations, models
import financial.models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_alter_lot_options_alter_lotmodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor')),
                ('split_condictions', models.PositiveIntegerField(default=0, help_text='As condições de parcelamento se referem ao pagamento pelo cartão de crédito', validators=[django.core.validators.MaxValueValidator(12)], verbose_name='Parcelas')),
                ('transaction_status', models.CharField(choices=[('PENDING', 'Cobrança aguardando pagamento'), ('CONFIRMED', 'Cobrança Confirmada'), ('RECEIVED', 'Cobrança Recebida'), ('RECEIVED_IN_CASH', 'Cobrança Recebida em Dinheiro'), ('OVERDUE', 'Cobrança Atrasada'), ('REFUND_REQUESTED', 'Estorno Solicitado'), ('REFUNDED', 'Cobrança Estornada'), ('CHARGEBACK_REQUESTED', 'Recebido chargeback'), ('CHARGEBACK_DISPUTE', 'Em disputa de chargeback'), ('AWAITING_CHARGEBACK_REVERSAL', 'Disputa vencida, aguardando repasse da adquirente'), ('DUNNING_REQUESTED', 'Em processo de recuperação'), ('DUNNING_RECEIVED', 'Recuperada'), ('AWAITING_RISK_ANALYSIS', 'Pagamento em análise')], default='PENDING', max_length=28, verbose_name='Status da Transação')),
                ('transaction_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Pagamento Asaas')),
                ('invoice_url', models.URLField(blank=True, max_length=240, null=True, verbose_name='Url de Pagamento')),
                ('due_date', models.DateField(default=financial.models.get_due_date, verbose_name='Data de Vencimento')),
                ('bank_slip_url', models.URLField(blank=True, max_length=240, null=True, verbose_name='Url do Boleto')),
                ('invoice_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='Número do pedido')),
                ('billing_type', models.CharField(blank=True, choices=[('CREDIT_CARD', 'Cartão de Crédito'), ('BOLETO', 'Boleto')], max_length=15, null=True, verbose_name='Método de pagamento')),
            ],
            options={
                'verbose_name': 'Histórico de Pagamento',
                'verbose_name_plural': 'Históricos de Pagamentos',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='lot',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Nome'),
        ),
    ]
