# Generated by Django 4.2 on 2023-04-23 14:11

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0005_rename_model_name_lotmodel_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=1, editable=False, max_length=150, populate_from='name', unique=True, verbose_name='Link'),
        ),
    ]
