# Generated by Django 4.2 on 2023-05-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0007_order_paymenthistory_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='billing_type',
            field=models.CharField(blank=True, choices=[('CREDIT_CARD', 'Cartão de Crédito'), ('BOLETO', 'Boleto'), ('PIX', 'Pix')], max_length=15, null=True, verbose_name='Método de pagamento'),
        ),
    ]
