# Generated by Django 4.2 on 2023-05-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0008_alter_paymenthistory_billing_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=80, verbose_name='Nome do banco')),
                ('bank_number', models.PositiveIntegerField(verbose_name='Número do banco')),
                ('agency', models.CharField(max_length=15, verbose_name='Agência')),
                ('account_number', models.CharField(max_length=25, verbose_name='Número da conta')),
                ('account_type', models.PositiveIntegerField(choices=[(1, 'Poupança'), (2, 'Corrente')], default=2)),
                ('phone_for_send_comprovation', models.CharField(max_length=30, verbose_name='Telefone para envio de comprovante')),
                ('document', models.PositiveIntegerField(verbose_name='Número de documento do responsável da conta')),
                ('type_document', models.PositiveIntegerField(default=1, verbose_name='Tipo de documento')),
            ],
            options={
                'verbose_name': 'Conta bancária',
                'verbose_name_plural': 'Contas bancárias',
            },
        ),
    ]
