# Generated by Django 4.2 on 2023-05-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0009_accountbank'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbank',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Se marcada as outras contas principais serão desativadas para recebimento', verbose_name='Conta ativa para recebimento?'),
        ),
        migrations.AlterField(
            model_name='accountbank',
            name='account_type',
            field=models.PositiveIntegerField(choices=[(1, 'Poupança'), (2, 'Corrente')], default=2, verbose_name='Tipo da conta'),
        ),
        migrations.AlterField(
            model_name='accountbank',
            name='type_document',
            field=models.PositiveIntegerField(choices=[(1, 'CNPJ'), (2, 'CPF')], default=1, verbose_name='Tipo de documento'),
        ),
    ]
