# Generated by Django 4.2 on 2023-05-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0010_accountbank_is_active_alter_accountbank_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbank',
            name='document',
            field=models.CharField(max_length=20, verbose_name='Número de documento do responsável da conta'),
        ),
    ]
