# Generated by Django 4.2 on 2023-05-08 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0013_accountbank_created_at_accountbank_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='installment_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor do parcelamento'),
        ),
        migrations.AddField(
            model_name='lot',
            name='number_of_installment',
            field=models.IntegerField(default=1, verbose_name='Quantidade de parcelas'),
        ),
    ]
