# Generated by Django 4.2 on 2023-05-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0016_alter_paymenthistory_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='qrcode_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='qrcode_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
