# Generated by Django 4.2 on 2023-06-02 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0017_alter_paymenthistory_qrcode_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Número do pedido'),
        ),
    ]
