# Generated by Django 4.2 on 2023-06-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0018_alter_paymenthistory_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='billing_type',
            field=models.CharField(blank=True, choices=[('CREDIT_CARD', 'Cartão de Crédito'), ('BOLETO', 'Boleto'), ('PIX', 'Pix'), ('CORTESIA', 'Vencedor do ultimo campeonato')], max_length=15, null=True, verbose_name='Método de pagamento'),
        ),
    ]
