# Generated by Django 4.2 on 2023-06-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0019_alter_paymenthistory_billing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='billing_type',
            field=models.CharField(blank=True, choices=[('CREDIT_CARD', 'Cartão de Crédito'), ('BOLETO', 'Boleto'), ('PIX', 'Pix'), ('CHAMPION', 'Vencedor do ultimo campeonato'), ('CORTESIA', 'Cortesia')], max_length=15, null=True, verbose_name='Método de pagamento'),
        ),
    ]
