# Generated by Django 4.2 on 2023-08-31 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0028_boleto_created_at_boleto_updated_at'),
        ('financial', '0020_alter_paymenthistory_billing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='registration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='competitor.registration', verbose_name='Inscrição'),
        ),
    ]
