# Generated by Django 4.2 on 2023-04-19 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Título')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Resposta')),
                ('question_status', models.CharField(choices=[('1', 'Ativo'), ('2', 'Ocultado')], default='1', max_length=1, verbose_name='Status da pergunta')),
            ],
        ),
        migrations.CreateModel(
            name='WebSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_start_date', models.DateField(blank=True, null=True, verbose_name='Data de Início do evento')),
                ('number_of_participants', models.IntegerField(blank=True, null=True, verbose_name='Quantidade de participantes')),
                ('number_of_states', models.IntegerField(blank=True, null=True, verbose_name='Quantidade de estados')),
                ('number_of_countries', models.IntegerField(blank=True, null=True, verbose_name='Quantidade de países')),
                ('facebook_url', models.CharField(blank=True, max_length=300, null=True, verbose_name='URL do Facebook')),
                ('instagram_url', models.CharField(blank=True, max_length=300, null=True, verbose_name='URL do Instagram')),
                ('youtube_url', models.CharField(blank=True, max_length=300, null=True, verbose_name='URL do YouTube')),
                ('whatsapp_url', models.TextField(blank=True, null=True, verbose_name='URL do Whatsapp')),
            ],
        ),
    ]
