# Generated by Django 4.2 on 2023-04-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={'verbose_name': 'Questão do FAQ', 'verbose_name_plural': 'Questões do FAQ'},
        ),
        migrations.AlterModelOptions(
            name='website',
            options={'verbose_name': 'Configuração do Site', 'verbose_name_plural': 'Configurações do Site'},
        ),
        migrations.AlterField(
            model_name='questions',
            name='question_status',
            field=models.BooleanField(default=True, help_text='Se ativa aparecerá no site', verbose_name='Ativa?'),
        ),
    ]
