# Generated by Django 4.2 on 2023-04-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_website_number_of_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='URL do Facebook'),
        ),
        migrations.AlterField(
            model_name='website',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='URL do Instagram'),
        ),
        migrations.AlterField(
            model_name='website',
            name='whatsapp_url',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='URL do Whatsapp'),
        ),
        migrations.AlterField(
            model_name='website',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='URL do YouTube'),
        ),
    ]
