# Generated by Django 4.2 on 2023-04-20 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_website_number_of_countries_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='question_status',
            new_name='is_active',
        ),
    ]
