# Generated by Django 4.2 on 2023-04-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_rename_question_status_questions_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='number_of_countries',
            field=models.PositiveIntegerField(blank=True, help_text='Coloque a quantidade de países que participaram no período do evento.', null=True, verbose_name='Quantidade de países'),
        ),
        migrations.AlterField(
            model_name='website',
            name='number_of_participants',
            field=models.PositiveIntegerField(blank=True, help_text='Colocar apenas número sem o milhar. Ex: 15 se for 15 mil.', null=True, verbose_name='Quantidade de participantes até hoje'),
        ),
        migrations.AlterField(
            model_name='website',
            name='number_of_states',
            field=models.PositiveIntegerField(blank=True, help_text='Coloque a quantidade de estados que participaram no período do evento.', null=True, verbose_name='Quantidade de estados'),
        ),
    ]
