# Generated by Django 4.2 on 2023-07-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_questions_created_at_questions_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition', models.PositiveIntegerField(verbose_name='Edition')),
                ('modality', models.CharField(max_length=100, verbose_name='Modality')),
                ('category', models.CharField(max_length=100, verbose_name='Category')),
                ('name', models.CharField(max_length=100, verbose_name='Competitor Name')),
                ('sponsorship', models.CharField(max_length=250, verbose_name='Sponsorship')),
                ('state', models.CharField(max_length=2, verbose_name='State')),
                ('vehicle', models.CharField(max_length=100, verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'Campeão',
                'verbose_name_plural': 'Campeões',
            },
        ),
    ]
