# Generated by Django 4.2 on 2023-07-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_champion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='sponsorship',
            field=models.CharField(max_length=500, verbose_name='Sponsorship'),
        ),
        migrations.AlterField(
            model_name='champion',
            name='state',
            field=models.CharField(max_length=50, verbose_name='State'),
        ),
    ]
