# Generated by Django 4.2 on 2023-07-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_champion_sponsorship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='sponsorship',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Sponsorship'),
        ),
    ]
