# Generated by Django 4.2 on 2023-07-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_champion_sponsorship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='champion',
            name='edition',
            field=models.PositiveIntegerField(verbose_name='Edição'),
        ),
        migrations.AlterField(
            model_name='champion',
            name='modality',
            field=models.CharField(max_length=100, verbose_name='Modalidade'),
        ),
        migrations.AlterField(
            model_name='champion',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome do Competidor'),
        ),
        migrations.AlterField(
            model_name='champion',
            name='sponsorship',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Patrocinador'),
        ),
        migrations.AlterField(
            model_name='champion',
            name='state',
            field=models.CharField(max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='champion',
            name='vehicle',
            field=models.CharField(max_length=100, verbose_name='Veículo'),
        ),
    ]
